# Sensor Extension build helper.
#
# 1. HMAC 시크릿 64자 hex 자동 생성 (또는 -HmacSecret 인자로 지정)
# 2. config.js 작성 (.gitignore 됨)
# 3. sensor_api_keys 등록용 SQL 출력 — Dashboard SQL Editor 에 붙여 실행
#
# 사용 예:
#   .\build.ps1 -SupabaseRef vzxvycbojpbmkzmjlvvy -DealerId dealer_001
#   .\build.ps1 -SupabaseRef ... -DealerId ... -KeyId ext_002 -HmacSecret <64hex>
#
# 이후: Chrome chrome://extensions → "압축해제된 확장 프로그램을 로드합니다" → 이 폴더 선택.

param(
  [Parameter(Mandatory=$true)] [string]$SupabaseRef,
  [Parameter(Mandatory=$true)] [string]$DealerId,
  [string]$KeyId = "ext_001",
  [string]$HmacSecret = "",
  [bool]$Debug = $false
)

$ErrorActionPreference = "Stop"

if (-not $HmacSecret) {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $HmacSecret = ($bytes | ForEach-Object { "{0:x2}" -f $_ }) -join ''
}
if ($HmacSecret.Length -ne 64 -or $HmacSecret -notmatch '^[0-9a-fA-F]+$') {
  throw "HmacSecret must be 64 hex chars (32 bytes)"
}

$apiBase = "https://${SupabaseRef}.supabase.co/functions/v1"
$here = Split-Path $MyInvocation.MyCommand.Path
$utf8 = New-Object System.Text.UTF8Encoding($false)

$configJs = @"
// AUTO-GENERATED by build.ps1 — DO NOT COMMIT.
export const CONFIG = {
  API_BASE: '$apiBase',
  API_KEY_ID: '$KeyId',
  HMAC_SECRET: '$HmacSecret',
  DEALER_ID: '$DealerId',
  DEBUG: $($Debug.ToString().ToLower()),
};
"@
[System.IO.File]::WriteAllText("$here\config.js", $configJs, $utf8)

Write-Host "[OK] config.js 작성 완료" -ForegroundColor Green
Write-Host "  API_BASE   : $apiBase"
Write-Host "  KEY_ID     : $KeyId"
Write-Host "  DEALER_ID  : $DealerId"
Write-Host "  HMAC (last 8) : ...$($HmacSecret.Substring($HmacSecret.Length-8))"
Write-Host ""

# DB 등록 SQL — Supabase Dashboard SQL Editor 에서 실행
$sql = @"

-- ============================================================
-- Sensor Extension API Key 등록 (Dashboard SQL Editor 에서 실행)
-- ============================================================
INSERT INTO sensor_api_keys (key_id, hmac_secret, dealer_id, expires_at, status)
VALUES (
  '$KeyId',
  '$HmacSecret',
  '$DealerId',
  now() + interval '1 year',
  'active'
)
ON CONFLICT (key_id) DO UPDATE
  SET hmac_secret = EXCLUDED.hmac_secret,
      dealer_id   = EXCLUDED.dealer_id,
      expires_at  = EXCLUDED.expires_at,
      status      = 'active',
      updated_at  = now();

-- 확인
SELECT key_id, dealer_id, status, expires_at FROM sensor_api_keys WHERE key_id = '$KeyId';
"@

$sqlPath = "$here\register_key.sql"
[System.IO.File]::WriteAllText($sqlPath, $sql, $utf8)

Write-Host "[NEXT] Supabase Dashboard SQL Editor 에 다음 SQL 실행:" -ForegroundColor Yellow
Write-Host "  https://supabase.com/dashboard/project/$SupabaseRef/sql/new"
Write-Host "  파일: $sqlPath"
Write-Host ""
Write-Host "[NEXT] Chrome chrome://extensions → '압축해제된 확장 프로그램을 로드' → '$here' 선택" -ForegroundColor Yellow
